//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportHand
    {
        public string GameID { get; set; }
        public string Stakes { get; set; }
        public string Game_Type { get; set; }
    }
}
